In [1]:
import torch 
torch.__version__

'2.12.1+cpu'

In [2]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get the python number within a tensor (only works with one-elkement tensor)

scalar.item()

7

In [5]:
# vector 

vector = torch.tensor([7,7])

vector

tensor([7, 7])

In [9]:
vector.ndim


1

In [10]:
vector.shape

torch.Size([2])

In [ ]:
# matrix 

matrix = torch.tensor([
        [7,8],
        [9,10]
    ])

matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [14]:
matrix.shape


torch.Size([2, 2])

In [16]:
# tensor 
tensor = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
]])

tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [22]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[0.3861, 0.4188, 0.0186, 0.9918],
         [0.9076, 0.4940, 0.2232, 0.6313],
         [0.7538, 0.4922, 0.6775, 0.7284]]),
 torch.float32,
 torch.Size([3, 4]))

In [23]:
random_tensor = torch.rand(size=(224,224, 3))
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[[0.9632, 0.1210, 0.5307],
          [0.2173, 0.8529, 0.3070],
          [0.5924, 0.2810, 0.1469],
          ...,
          [0.4198, 0.6993, 0.2677],
          [0.5909, 0.2658, 0.3860],
          [0.9556, 0.7296, 0.6715]],
 
         [[0.3467, 0.8870, 0.4520],
          [0.4194, 0.2173, 0.6151],
          [0.0250, 0.0887, 0.8755],
          ...,
          [0.2699, 0.1402, 0.1300],
          [0.8174, 0.5518, 0.3046],
          [0.7316, 0.3700, 0.3456]],
 
         [[0.6966, 0.1230, 0.0674],
          [0.6765, 0.8848, 0.9441],
          [0.9521, 0.4161, 0.5605],
          ...,
          [0.1884, 0.4888, 0.0132],
          [0.4974, 0.0863, 0.6458],
          [0.4771, 0.4244, 0.5687]],
 
         ...,
 
         [[0.1286, 0.2602, 0.7885],
          [0.5205, 0.4298, 0.4146],
          [0.7214, 0.6340, 0.7200],
          ...,
          [0.3279, 0.1426, 0.1755],
          [0.5800, 0.3286, 0.5530],
          [0.4873, 0.6657, 0.8089]],
 
         [[0.9993, 0.4353, 0.4072],
          [0

In [24]:
zeros = torch.zeros([3,4])
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [25]:
ones = torch.ones([3,4])
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [29]:
zero_to_ten_deprecated = torch.range(0,10)
zero_to_ten_deprecated

C:\Users\perry\AppData\Local\Temp\ipykernel_35736\1643260326.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

ten_ones = torch.ones_like(input=ten_zeros)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)

float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.Size([3]), torch.float32, device(type='cpu'))

In [41]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [43]:
some_tensor = torch.rand([3,4])

print(some_tensor)
print(f"shape of tensor: {some_tensor.shape}")
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"device tensor is stored on: {some_tensor.device}")

tensor([[0.2026, 0.4066, 0.8565, 0.0621],
        [0.5710, 0.7666, 0.9818, 0.2968],
        [0.2307, 0.5269, 0.3851, 0.0018]])
shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device tensor is stored on: cpu


In [44]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [45]:
tensor*10

tensor([10, 20, 30])

In [46]:
tensor

tensor([1, 2, 3])

In [47]:
tensor -= 10
tensor

tensor([-9, -8, -7])

In [48]:
tensor += 10

tensor

tensor([1, 2, 3])

In [ ]:
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [51]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [52]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [59]:
tensor = torch.tensor([1,2,3])

tensor.shape

torch.Size([3])

In [54]:
#element wise matrix multiplication
tensor*tensor

tensor([ 9, 16])

In [55]:
tensor@tensor

tensor(25)

In [57]:
torch.matmul(tensor, tensor)

tensor(25)

In [60]:
%%time

value = 0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [61]:
%%time

torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)