In [1]:
import torch 
torch.__version__

'2.12.1+cpu'

In [2]:
# scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get the python number within a tensor (only works with one-elkement tensor)

scalar.item()

7

In [5]:
# vector 

vector = torch.tensor([7,7])

vector

tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix 

matrix = torch.tensor([
        [7,8],
        [9,10]
    ])

matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape


torch.Size([2, 2])

In [11]:
# tensor 
tensor = torch.tensor([[
    [1,2,3],
    [3,6,9],
    [2,4,5]
]])

tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
# create a random tensor of size (3,4)

random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[0.2993, 0.6893, 0.6068, 0.7855],
         [0.2707, 0.7669, 0.7030, 0.9442],
         [0.7751, 0.4049, 0.9599, 0.6451]]),
 torch.float32,
 torch.Size([3, 4]))

In [15]:
random_tensor = torch.rand(size=(224,224, 3))
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[[0.0973, 0.5231, 0.3838],
          [0.7407, 0.0460, 0.2955],
          [0.1111, 0.2853, 0.1288],
          ...,
          [0.7739, 0.5549, 0.5791],
          [0.4715, 0.5965, 0.9538],
          [0.4992, 0.6027, 0.2423]],
 
         [[0.0609, 0.5130, 0.9725],
          [0.6347, 0.8178, 0.2780],
          [0.5852, 0.6639, 0.6868],
          ...,
          [0.2119, 0.7388, 0.5365],
          [0.6860, 0.9710, 0.0151],
          [0.8133, 0.0924, 0.5399]],
 
         [[0.7496, 0.9505, 0.3146],
          [0.8692, 0.9672, 0.7033],
          [0.2606, 0.5427, 0.8942],
          ...,
          [0.6219, 0.7997, 0.5888],
          [0.2302, 0.2027, 0.0823],
          [0.9436, 0.9836, 0.2564]],
 
         ...,
 
         [[0.9771, 0.2541, 0.8929],
          [0.1036, 0.5950, 0.4859],
          [0.5958, 0.9244, 0.7244],
          ...,
          [0.3718, 0.9347, 0.6465],
          [0.6347, 0.3684, 0.6790],
          [0.6292, 0.6037, 0.8797]],
 
         [[0.3480, 0.1652, 0.1465],
          [0

In [16]:
zeros = torch.zeros([3,4])
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones([3,4])
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [18]:
zero_to_ten_deprecated = torch.range(0,10)
zero_to_ten_deprecated

C:\Users\perry\AppData\Local\Temp\ipykernel_23724\1643260326.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

ten_ones = torch.ones_like(input=ten_zeros)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)

float_32_tensor, float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=torch.float16)

float_16_tensor.dtype

torch.float16

In [23]:
some_tensor = torch.rand([3,4])

print(some_tensor)
print(f"shape of tensor: {some_tensor.shape}")
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"device tensor is stored on: {some_tensor.device}")

tensor([[0.5022, 0.0054, 0.9284, 0.0016],
        [0.7032, 0.9372, 0.8632, 0.5769],
        [0.6053, 0.6351, 0.2692, 0.0265]])
shape of tensor: torch.Size([3, 4])
datatype of tensor: torch.float32
device tensor is stored on: cpu


In [24]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [25]:
tensor*10

tensor([10, 20, 30])

In [26]:
tensor

tensor([1, 2, 3])

In [27]:
tensor -= 10
tensor

tensor([-9, -8, -7])

In [28]:
tensor += 10

tensor

tensor([1, 2, 3])

In [29]:
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [30]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [31]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [32]:
tensor = torch.tensor([1,2,3])

tensor.shape

torch.Size([3])

In [33]:
#element wise matrix multiplication
tensor*tensor

tensor([1, 4, 9])

In [34]:
tensor@tensor

tensor(14)

In [35]:
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
%%time

value = 0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 499 μs


tensor(14)

In [37]:
%%time

torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 501 μs


tensor(14)

In [38]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype = torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [39]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [41]:
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(output.shape)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
torch.Size([3, 3])


In [42]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [45]:
tensor_A @ tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

$$ y = x\cdot{A^T} + b $$

In [52]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features = 3,
                         out_features = 10)

x = tensor_A.T
output = linear(x)
print(x.shape)
print(output)
print(output.shape)

torch.Size([2, 3])
tensor([[ 1.7241,  0.2429,  3.7266,  1.7183,  1.8656,  2.0372, -1.0681,  1.6103,
         -2.0063, -3.2169],
        [ 2.5095,  0.7633,  4.2936,  1.9046,  2.6487,  2.4860, -1.4565,  1.6911,
         -2.8912, -4.0798]], grad_fn=<AddmmBackward0>)
torch.Size([2, 10])


In [54]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
print(x.min())
print(x.max())
print(x.type(torch.float32).mean())
print(x.sum())

tensor(0)
tensor(90)
tensor(45.)
tensor(450)


In [59]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [64]:
tensor = torch.arange(10,100,10)
print(tensor)
print(tensor.dtype)
print(tensor.argmax())
print(tensor.argmin())

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64
tensor(8)
tensor(0)


In [65]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [66]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16.dtype

torch.float16

In [69]:
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8)

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


In [70]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [79]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [80]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [81]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [86]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [87]:
print(x_reshaped)
print(x_reshaped.shape)

tensor([[5., 2., 3., 4., 5., 6., 7.]])
torch.Size([1, 7])


In [88]:
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [92]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [93]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
