In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float) # overides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5367, 0.3793],
        [0.9031, 0.1765]]) 



In [5]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8416, 0.9231, 0.5094],
        [0.1317, 0.8625, 0.8828]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatypes of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatypes of tensor: torch.float32
Device tensor is stored on: cpu


In [7]:
# we move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [8]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column {tensor[..., -1]}")
print(tensor)
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
# this computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ''tensor.T'' returns the transpose of a tensor

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# this computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [12]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [13]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [14]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [15]:
n = np.ones(5)
t = torch.from_numpy(n)

In [16]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


10 exercises to code yourself

1. Create
Make a 3×4 tensor of random values. Print shape and dtype.

In [17]:
shape = (3,4)
rand = torch.rand(shape)
print(rand)

print(rand.shape)
print(rand.dtype)

tensor([[0.8545, 0.0505, 0.9249, 0.9373],
        [0.5649, 0.1552, 0.8850, 0.1999],
        [0.8769, 0.5631, 0.7770, 0.2211]])
torch.Size([3, 4])
torch.float32


2. Reshape
Create a 12-element tensor. Reshape to 3×4, then to 2×2×3. Print each shape.

In [18]:
shape = (3,4)
shape_n = torch.ones(3,4)
print(shape_n)



tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


3. Slice & index
Create a 5×5 tensor. Extract the top-left 3×3 block, then the first column, then the last row.

In [19]:
shape = (5,5)
tensor = torch.rand(shape)
print(tensor)
print(f" top left 3x3 {tensor[:3,:3]}")
print(f" first column: {tensor[:,0]}")
print(f" first row: {tensor[-1,:]}")

tensor([[0.6438, 0.6258, 0.5731, 0.5801, 0.8766],
        [0.3370, 0.3865, 0.0418, 0.6284, 0.2272],
        [0.9242, 0.6830, 0.1597, 0.3556, 0.9641],
        [0.9684, 0.6968, 0.8885, 0.0736, 0.6663],
        [0.4794, 0.6456, 0.4942, 0.5070, 0.0796]])
 top left 3x3 tensor([[0.6438, 0.6258, 0.5731],
        [0.3370, 0.3865, 0.0418],
        [0.9242, 0.6830, 0.1597]])
 first column: tensor([0.6438, 0.3370, 0.9242, 0.9684, 0.4794])
 first row: tensor([0.4794, 0.6456, 0.4942, 0.5070, 0.0796])


4. Element-wise ops
Create two 3×3 tensors. Add them, multiply them element-wise, divide one by the other.

In [38]:

a = torch.rand(3, 3)
print(a)
b = torch.rand(3, 3)
print(b)
# Element-wise add
sum_ab = a + b  # or torch.add(a, b)
print(f"Add: {sum_ab}")

# Element-wise multiply
mul_ab = a * b  # or torch.mul(a, b)
print(f"Multiply: {mul_ab}")

# Element-wise divide
div_ab = a / b  # or torch.div(a, b)
print(f"Divide: {div_ab}")

tensor([[0.5475, 0.6754, 0.4288],
        [0.2095, 0.3679, 0.5584],
        [0.2471, 0.6169, 0.4255]])
tensor([[0.7165, 0.5799, 0.7158],
        [0.6332, 0.0322, 0.2109],
        [0.0659, 0.5351, 0.8129]])
Add: tensor([[1.2640, 1.2553, 1.1446],
        [0.8427, 0.4001, 0.7693],
        [0.3130, 1.1520, 1.2384]])
Multiply: tensor([[0.3923, 0.3916, 0.3069],
        [0.1326, 0.0119, 0.1178],
        [0.0163, 0.3301, 0.3459]])
Divide: tensor([[ 0.7642,  1.1648,  0.5990],
        [ 0.3308, 11.4202,  2.6475],
        [ 3.7485,  1.1528,  0.5234]])


5. Matrix multiply
Create a 3×4 and a 4×2 tensor. Multiply them (use @ or torch.matmul). Verify shape is 3×2.

In [ ]:
a = torch.rand((3,4))
b = torch.rand((4,2))

new = a.matmul(b)
print(new.shape)

tensor([[0.8482, 0.6358, 0.7924, 0.0712],
        [0.2823, 0.5102, 0.5896, 0.4869],
        [0.2981, 0.4390, 0.3089, 0.1452]])
tensor([[0.2715, 0.4415],
        [0.3594, 0.2060],
        [0.0878, 0.5813],
        [0.2279, 0.1546]])
torch.Size([3, 2])
tensor([[0.5446, 0.9771],
        [0.4227, 0.6477],
        [0.2989, 0.4241]])


6. Broadcasting
Create a 3×4 tensor and a shape-4 1D tensor. Add them (broadcasts to 3×4). Verify result shape.

In [24]:
a = torch.rand([3,4])
b = torch.ones(4)

print(a)
print(b)
new = a + b
print(new)

tensor([[0.5921, 0.2742, 0.8069, 0.5640],
        [0.4348, 0.3507, 0.8949, 0.7297],
        [0.8134, 0.3355, 0.3272, 0.1581]])
tensor([1., 1., 1., 1.])
tensor([[1.5921, 1.2742, 1.8069, 1.5640],
        [1.4348, 1.3507, 1.8949, 1.7297],
        [1.8134, 1.3355, 1.3272, 1.1581]])


7. Tensor → NumPy
Create a tensor, convert to NumPy array. Modify the NumPy array. Check if tensor changed (shared memory).

In [39]:
t = torch.ones(4)
print(t)
print(t.dtype)

n = t.numpy()
print(n)
print(t)
np.add(n, 1, out = n)

print(n)
print(t)

tensor([1., 1., 1., 1.])
torch.float32
[1. 1. 1. 1.]
tensor([1., 1., 1., 1.])
[2. 2. 2. 2.]
tensor([2., 2., 2., 2.])


8. NumPy → Tensor
Create a NumPy array (numpy.arange), convert to tensor. Print both types.

In [40]:
n = np.ones(5)
t = torch.from_numpy(n)

print(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


9. Reduction ops
Create a 4×5 tensor. Sum all elements, sum along rows (axis 0), sum along columns (axis 1).

In [44]:
tensor = torch.rand(4, 5)

print(f"Sum all: {tensor.sum()}")           # single number
print(f"Sum along axis 0 (rows): {tensor.sum(dim=0)}")    # sums each column
print(f"Sum along axis 1 (cols): {tensor.sum(dim=1)}")    # sums each row

Sum all: 11.533312797546387
Sum along axis 0 (rows): tensor([2.0807, 1.6867, 2.8486, 3.1702, 1.7471])
Sum along axis 1 (cols): tensor([3.9757, 2.6340, 2.3150, 2.6085])


10. Combine (challenge)
Create two random 2×3 tensors. Stack them (torch.stack). Reshape the result to 2×6. Convert to NumPy.

In [47]:
tensor = torch.rand([2,3])
tensor2 = torch.rand([2,3])

print(tensor)
print(tensor2)

new = torch.stack([tensor, tensor2])

print(new)
print(new.dtype)

newnew = new.reshape([2,6])
print(newnew)

newnew_n = newnew.numpy()
print(newnew_n)

tensor([[0.6479, 0.5122, 0.2733],
        [0.2408, 0.6415, 0.3000]])
tensor([[0.0480, 0.7170, 0.8813],
        [0.6677, 0.0233, 0.2624]])
tensor([[[0.6479, 0.5122, 0.2733],
         [0.2408, 0.6415, 0.3000]],

        [[0.0480, 0.7170, 0.8813],
         [0.6677, 0.0233, 0.2624]]])
torch.float32
tensor([[0.6479, 0.5122, 0.2733, 0.2408, 0.6415, 0.3000],
        [0.0480, 0.7170, 0.8813, 0.6677, 0.0233, 0.2624]])
[[0.6479391  0.5122419  0.2732576  0.24083793 0.64145935 0.29998112]
 [0.04802597 0.7170461  0.8812988  0.66767865 0.0233084  0.26241606]]
